#!/usr/bin/env python3
##############################################################################
# Description:
#
# This is a custom script written for the specific purpose of manipulating
# the ephemeris CSV file used for the TAC System.
#
# 
#
# This script reads in an input CSV file that was generated by script
# 'createLongitudeSpreadsheetFile_forTacSystem.py', and then does
# various operations to add fields values.  This final set of data is
# written to another CSV file.
#
##############################################################################

# Number of lines to skip before reading the data.
linesToSkip = 1

# Delimiter.
delimiter = ","

inputFilename = "TacEphemeris.csv"
outputFilename = "TacEphemeris2.csv"


##############################################################################

import os
import sys 
import errno

##############################################################################

# Lines of text that will go into the output file.
outputFileLines = []
outputFileLines.append(\
    "[0] Date," + \
    "[1] Day," + \
    "[2] Mercury," + \
    "[3] Venus," + \
    "[4] Earth," + \
    "[5] Mars," + \
    "[6] Jupiter," + \
    "[7] Saturn," + \
    "[8] Uranus," + \
    "[9] Neptune," + \
    "[10] Pluto," + \
    "[11] Isis," + \
    "[12] Mars - Saturn," + \
    "[13] (Mars - Saturn) % 360," + \
    "[14] (Mars - Saturn) % 12," + \
    "[15] Mars - Saturn + Earth," + \
    "[16] (Mars - Saturn + Earth) % 360," + \
    "[17] (Mars - Saturn + Earth) % 10")


print("Processing input file...")

# Counter for the current line number.
lineNum = 0

with open(inputFilename) as f:
    for line in f:
        if lineNum >= linesToSkip:
            line = line.strip()
            fieldValues = line.split(delimiter)

            # Make a special manual +360 adjustments for planets, so
            # composite calculations will come out positive.  Each
            # faster planet gets another multiple of 360 added to its
            # longitude.
            j = 0
            for i in range(len(fieldValues) - 1, 1, -1):
                fieldValues[i] = str(float(fieldValues[i]) + (360.0 * j))
                j += 1

            mercuryLongitude = float(fieldValues[2])
            venusLongitude = float(fieldValues[3])
            earthLongitude = float(fieldValues[4])
            marsLongitude = float(fieldValues[5])
            jupiterLongitude = float(fieldValues[6])
            saturnLongitude = float(fieldValues[7])
            uranusLongitude = float(fieldValues[8])
            neptuneLongitude = float(fieldValues[9])
            plutoLongitude = float(fieldValues[10])
            isisLongitude = float(fieldValues[11])
            
            diffMarsSaturn = marsLongitude - saturnLongitude
            diffMarsSaturnMod360 = diffMarsSaturn % 360
            diffMarsSaturnMod12 = diffMarsSaturn % 12
            
            diffMarsSaturnPlusEarth = \
                marsLongitude - saturnLongitude + earthLongitude
            
            diffMarsSaturnPlusEarthMod360 = diffMarsSaturnPlusEarth % 360
            diffMarsSaturnPlusEarthMod10 = diffMarsSaturnPlusEarth % 10

            outputLine = ""
            for i in range(len(fieldValues)):
                outputLine += fieldValues[i] + ","
                
            outputLine += \
                       str(diffMarsSaturn) + "," + \
                       str(diffMarsSaturnMod360) + "," + \
                       str(diffMarsSaturnMod12) + "," + \
                       str(diffMarsSaturnPlusEarth) + "," + \
                       str(diffMarsSaturnPlusEarthMod360) + "," + \
                       str(diffMarsSaturnPlusEarthMod10)
            
            outputFileLines.append(outputLine)

        # Increment the line number counter.
        lineNum += 1


# Write output file.
print("Writing to output file...")

with open(outputFilename, "wt") as f:
    for line in outputFileLines:
        f.write(line + os.linesep)

print("Done.")

##############################################################################
