#!/usr/bin/env python3
##############################################################################
# Description:
#
# This is a custom script written for the specific purpose of manipulating
# the ephemeris CSV file used for cycle hunting.
#
# 
#
# This script reads in an input CSV file that was generated by script
# 'createLongitudeSpreadsheetFileForCycleHunting.py', and then does
# various operations to add fields values.  This final set of data is
# written to another CSV file.
#
##############################################################################

# Number of lines to skip before reading the data.
linesToSkip = 1

# Delimiter.
delimiter = ","

inputFilename = "PAAS_Ephemeris.csv"
outputFilename = "PAAS_Ephemeris2.csv"


##############################################################################

import os
import sys 
import errno

##############################################################################

# Column headers.
columnHeaders = []
columnHeaders.append("Date")
columnHeaders.append("Day")
columnHeaders.append("Mercury")
columnHeaders.append("Venus")
columnHeaders.append("Earth")
columnHeaders.append("Mars")
columnHeaders.append("Jupiter")
columnHeaders.append("Saturn")
columnHeaders.append("Uranus")
columnHeaders.append("Neptune")
columnHeaders.append("Pluto")
columnHeaders.append("Isis")
columnHeaders.append("Mercury - Venus")
columnHeaders.append("Mercury - Earth")
columnHeaders.append("Mercury - Mars")
columnHeaders.append("Mercury - Jupiter")
columnHeaders.append("Mercury - Saturn")
columnHeaders.append("Mercury - Uranus")
columnHeaders.append("Mercury - Neptune")
columnHeaders.append("Mercury - Pluto")
columnHeaders.append("Mercury - Isis")
columnHeaders.append("Venus - Earth")
columnHeaders.append("Venus - Mars")
columnHeaders.append("Venus - Jupiter")
columnHeaders.append("Venus - Saturn")
columnHeaders.append("Venus - Uranus")
columnHeaders.append("Venus - Neptune")
columnHeaders.append("Venus - Pluto")
columnHeaders.append("Venus - Isis")
columnHeaders.append("Earth - Mars")
columnHeaders.append("Earth - Jupiter")
columnHeaders.append("Earth - Saturn")
columnHeaders.append("Earth - Uranus")
columnHeaders.append("Earth - Neptune")
columnHeaders.append("Earth - Pluto")
columnHeaders.append("Earth - Isis")
columnHeaders.append("Mars - Jupiter")
columnHeaders.append("Mars - Saturn")
columnHeaders.append("Mars - Uranus")
columnHeaders.append("Mars - Neptune")
columnHeaders.append("Mars - Pluto")
columnHeaders.append("Mars - Isis")
columnHeaders.append("Jupiter - Saturn")
columnHeaders.append("Jupiter - Uranus")
columnHeaders.append("Jupiter - Neptune")
columnHeaders.append("Jupiter - Pluto")
columnHeaders.append("Jupiter - Isis")
columnHeaders.append("Saturn - Uranus")
columnHeaders.append("Saturn - Neptune")
columnHeaders.append("Saturn - Pluto")
columnHeaders.append("Saturn - Isis")
columnHeaders.append("Uranus - Neptune")
columnHeaders.append("Uranus - Pluto")
columnHeaders.append("Uranus - Isis")
columnHeaders.append("Neptune - Pluto")
columnHeaders.append("Neptune - Isis")
columnHeaders.append("Pluto - Isis")

# Prepend the index to the column headers.
for i in range(len(columnHeaders)):
    columnHeaders[i] = "[{}] ".format(i) + columnHeaders[i]

# Compose the header line of text.
headerLine = ""
for columnHeader in columnHeaders:
    headerLine += columnHeader + ","

# Remove trailing comma.
headerLine = headerLine[:-1]
    
# Lines of text that will go into the output file.
outputFileLines = []
outputFileLines.append(headerLine)

print("Processing input file...")

# Counter for the current line number.
lineNum = 0

with open(inputFilename) as f:
    for line in f:
        if lineNum >= linesToSkip:
            line = line.strip()
            fieldValues = line.split(delimiter)

            # Make a special manual +360 adjustments for planets, so
            # composite calculations will come out positive.  Each
            # faster planet gets another multiple of 360 added to its
            # longitude.
            j = 0
            for i in range(len(fieldValues) - 1, 1, -1):
                fieldValues[i] = str(float(fieldValues[i]) + (360.0 * j))
                j += 1

            mercuryLongitude = float(fieldValues[2])
            venusLongitude = float(fieldValues[3])
            earthLongitude = float(fieldValues[4])
            marsLongitude = float(fieldValues[5])
            jupiterLongitude = float(fieldValues[6])
            saturnLongitude = float(fieldValues[7])
            uranusLongitude = float(fieldValues[8])
            neptuneLongitude = float(fieldValues[9])
            plutoLongitude = float(fieldValues[10])
            isisLongitude = float(fieldValues[11])

            diffMarsSaturn = marsLongitude - saturnLongitude
            diffMarsSaturnMod360 = diffMarsSaturn % 360
            diffMarsSaturnMod12 = diffMarsSaturn % 12
            
            diffMarsSaturnPlusEarth = \
                marsLongitude - saturnLongitude + earthLongitude
            
            diffMarsSaturnPlusEarthMod360 = diffMarsSaturnPlusEarth % 360
            diffMarsSaturnPlusEarthMod10 = diffMarsSaturnPlusEarth % 10

            outputLine = ""
            for i in range(len(fieldValues)):
                outputLine += fieldValues[i] + ","
                
            outputLine += \
                       str(mercuryLongitude - venusLongitude) + "," + \
                       str(mercuryLongitude - earthLongitude) + "," + \
                       str(mercuryLongitude - marsLongitude) + "," + \
                       str(mercuryLongitude - jupiterLongitude) + "," + \
                       str(mercuryLongitude - saturnLongitude) + "," + \
                       str(mercuryLongitude - uranusLongitude) + "," + \
                       str(mercuryLongitude - neptuneLongitude) + "," + \
                       str(mercuryLongitude - plutoLongitude) + "," + \
                       str(mercuryLongitude - isisLongitude) + "," + \
                       str(venusLongitude - earthLongitude) + "," + \
                       str(venusLongitude - marsLongitude) + "," + \
                       str(venusLongitude - jupiterLongitude) + "," + \
                       str(venusLongitude - saturnLongitude) + "," + \
                       str(venusLongitude - uranusLongitude) + "," + \
                       str(venusLongitude - neptuneLongitude) + "," + \
                       str(venusLongitude - plutoLongitude) + "," + \
                       str(venusLongitude - isisLongitude) + "," + \
                       str(earthLongitude - marsLongitude) + "," + \
                       str(earthLongitude - jupiterLongitude) + "," + \
                       str(earthLongitude - saturnLongitude) + "," + \
                       str(earthLongitude - uranusLongitude) + "," + \
                       str(earthLongitude - neptuneLongitude) + "," + \
                       str(earthLongitude - plutoLongitude) + "," + \
                       str(earthLongitude - isisLongitude) + "," + \
                       str(marsLongitude - jupiterLongitude) + "," + \
                       str(marsLongitude - saturnLongitude) + "," + \
                       str(marsLongitude - uranusLongitude) + "," + \
                       str(marsLongitude - neptuneLongitude) + "," + \
                       str(marsLongitude - plutoLongitude) + "," + \
                       str(marsLongitude - isisLongitude) + "," + \
                       str(jupiterLongitude - saturnLongitude) + "," + \
                       str(jupiterLongitude - uranusLongitude) + "," + \
                       str(jupiterLongitude - neptuneLongitude) + "," + \
                       str(jupiterLongitude - plutoLongitude) + "," + \
                       str(jupiterLongitude - isisLongitude) + "," + \
                       str(saturnLongitude - uranusLongitude) + "," + \
                       str(saturnLongitude - neptuneLongitude) + "," + \
                       str(saturnLongitude - plutoLongitude) + "," + \
                       str(saturnLongitude - isisLongitude) + "," + \
                       str(uranusLongitude - neptuneLongitude) + "," + \
                       str(uranusLongitude - plutoLongitude) + "," + \
                       str(uranusLongitude - isisLongitude) + "," + \
                       str(neptuneLongitude - plutoLongitude) + "," + \
                       str(neptuneLongitude - isisLongitude) + "," + \
                       str(plutoLongitude - isisLongitude) + ","

            # Remove trailing comma.
            outputLine = outputLine[:-1]
            
            outputFileLines.append(outputLine)
        
        # Increment the line number counter.
        lineNum += 1


# Write output file.
print("Writing to output file...")

with open(outputFilename, "wt") as f:
    for line in outputFileLines:
        f.write(line + os.linesep)

print("Done.")

##############################################################################
